use urls instead of path strings, do not rely on FileManager.currentPath
ryanbaldwin/Cute pull request #2
Opened 2019-03-05 21:37 UTC by xinsight

This addresses #1. The main change is not rely on the FileManager's "current directory", and instead use absolute paths. I also updated the code to use the FileManager's more modern URL methods (instead of String paths). All tests pass. Comments appreciated!

2019-03-14 01:23 UTC, ryanbaldwin requested changes
a couple of minor change requests, but overall I think this looks good. My CI apparently is not working on the PR, but I'll try and fix that. I have a Swift 4.2 branch open right now which I'll use as a testbed.

Cheers!

2019-03-14 01:23 UTC, ryanbaldwin commented on Cute/Impl/FileBasedPersister.swift
> +    private let queueName: String
heh - thanks for this. And also for the spelling fix... I'm going to miss good ol' `applicatinSupportDirectory` from the apparent deep south.

2019-03-14 01:23 UTC, ryanbaldwin commented on Cute/Impl/FileBasedPersister.swift
> +                return nil
What's the reason for doing a try/catch here instead of just letting it fail? I'd recommend either re-throwing or just ditch the try/catch.

2019-03-14 01:23 UTC, ryanbaldwin commented on Cute/Impl/FileBasedPersister.swift
> +            files = []
I've gone back and forth on this. At this level (Framework), I think it's best to bubble up the error and let the consumer determine what they want to do with this. That error could point to a bug in their environment, setup, etc. Given that we don't know what the error is, or that we care at this level (and that Cute actually supports tvOS and macOS), I think it's best to let the error bubble up.

2019-03-14 19:46 UTC, xinsight commented on Cute/Impl/FileBasedPersister.swift
> +            files = []
Yes, makes sense. Almost all of the methods in FilePersister throw, so might as well be consistent. I did run into one problem... in the drain method i cannot throw from within a dispatched block. So, i just had to print the error out like an animal.

2019-03-16 13:07 UTC, ryanbaldwin approved these changes

2019-03-16 13:08 UTC, ryanbaldwin commented
Approved. There's a failing test, but that failing test is also on master. It's something I'm attempting to fix on a different branch so ignore it.

thanks for this!

2019-03-21 00:47 UTC, merged